#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>

import argparse
import subprocess

__docformat__ = "restructuredtext en"

def main():
    options = _parse_args()


def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("args", metavar="keyword", type=str, nargs=1, help="Positional arguments.")

    return parser.parse_args()


if __name__ == "__main__":
    main()
