#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013-2014 Martin Ueding <dev@martin-ueding.de>

"""
This will find the LaTeX documentation for a given package.

You can use this as a keywordprg in Vim, so that you can move the cursor over
``package`` in ``\includepackage{package}`` and press ``K``. Then, it will
search for ``package.pdf`` on your disk and open it in your default PDF viewer.
"""

import argparse
import subprocess
import sys

__docformat__ = "restructuredtext en"

def search_for_file(filename):
    try:
        command = ["locate", "-b", r"\{0}.pdf".format(filename)]
        print(command)
        findings = subprocess.check_output(command).split(b"\n")[:-1]
        print(findings)
        return findings
    except subprocess.CalledProcessError as e:
        print(e)
        return []

def open_path(path):
    try:
        subprocess.check_call(["xdg-open", path])
    except subprocess.CalledProcessError as e:
        print(e)
        sys.exit(1)

def main():
    options = _parse_args()

    search_for_file(options.keyword)




def _parse_args():
    """
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    """
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("keyword", help="Package name or keyword")

    return parser.parse_args()

if __name__ == "__main__":
    main()
